MyNeighborhood/MyNeighborhood/Models/Property.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Property.cs" company="MyNeighborhood">
//   Pascual Maestre. MyNeighborhood
// </copyright>
// <summary>
//   Defines the Property type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace MyNeighborhood.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// The property.
    /// </summary>
    public class Property
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the number.
        /// </summary>
        [Required]
        public int Number { get; set; }

        /// <summary>
        /// Gets or sets the floor.
        /// </summary>
        public string Floor { get; set; }

        /// <summary>
        /// Gets or sets the door.
        /// </summary>
        public string Door { get; set; }

        #region RelationShips

        /// <summary>
        /// Gets or sets the owner id.
        /// </summary>
        [ForeignKey("UserInfo")]
        public int? OwnerId { get; set; }
        
        /// <summary>
        /// Gets or sets the user info.
        /// </summary>
        public UserInfo UserInfo { get; set; }

        /// <summary>
        /// Gets or sets the comunity id.
        /// </summary>
        [ForeignKey("Comunity")]
        [Required]
        public Guid ComunityId { get; set; }

        /// <summary>
        /// Gets or sets the house comunity.
        /// </summary>
        [Required]
        public Comunity Comunity { get; set; }

        /// <summary>
        /// Gets or sets the type property id.
        /// </summary>
        [ForeignKey("Type")]
        [Required]
        public Guid TypePropertyId { get; set; }
        
        /// <summary>
        /// Gets or sets the property type.
        /// </summary>
        [Required]
        public TypeProperty Type { get; set; }

        #endregion
    }
}

MyNeighborhood/MyNeighborhood/Controllers/PropertyController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PropertyController.cs" company="MyNeighborhood">
//   Pascual MAestre. MyNeighborhood.
// </copyright>
// <summary>
//   Defines the PropertiesController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace MyNeighborhood.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Net;
    using System.Web.Mvc;

    using global::MyNeighborhood.App_GlobalResources;
    using global::MyNeighborhood.Models;

    using Microsoft.AspNet.Identity;

    /// <summary>
    /// The properties controller.
    /// </summary>
    [Authorize]
    public class PropertyController : MyNeighborhood
    {
        /// GET: Properties
        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator)]
        public ActionResult Index()
        {
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            if (!isAdmin)
            {
                return this.HttpNotFound();
            }

            var properties = this.DbContextContainer.PropertyData.GetAllProperties();
            return this.View(properties);
        }

        /// <summary>
        /// The index comunity.
        /// </summary>
        /// <param name="comunityId">
        /// The comuniti id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult IndexComunity(Guid? comunityId)
        {
            if (comunityId != null && comunityId != Guid.Empty)
            {
                var comunity = this.DbContextContainer.ComunityData.GetComunity(comunityId);
                var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);
                var isDirectorsBoardOfComunit = this.User.IsInRole(RoleNames.RoleDirectorsBorard)
                                                 && this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.ManagedComunities.Contains(comunity);

                if (!isAdmin && !isDirectorsBoardOfComunit)
                {
                    return this.HttpNotFound();
                }

                this.ViewBag.ReturnUrl = this.Url.Action("Edit", "Comunities", new { id = comunityId });
                
                var properties = this.DbContextContainer.PropertyData.GetAllPropertiesByComunity(comunityId);
                return this.PartialView("Index", properties);
            }

            return this.PartialView("Index");
        }

        /// <summary>
        /// The index neihbor.
        /// </summary>
        /// <param name="neighborId">
        /// The neighbor id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleNeighbor)]
        public ActionResult IndexNeihbor(string neighborId)
        {
            var isNeighbor = this.UserManager.IsInRole(neighborId, RoleNames.RoleNeighbor);

            if (isNeighbor)
            {
                var properties = this.DbContextContainer.PropertyData.GetAllPropertiesByNeighbor(neighborId);

                return this.View("Index", properties);
            }

            return this.View("Index");
        }

        /// GET: Properties/Create
        /// <summary>
        /// The create.
        /// </summary>
        /// <param name="returnUrl">
        /// The return Url.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Create(string returnUrl)
        {
            this.ViewBag.ReturnUrl = returnUrl;
            
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            this.ViewBag.ComunityId = this.DbContextContainer.ComunityData.GetAllManagedComunitiesSelect(!isAdmin ? this.User.Identity.GetUserId() : null);
            this.ViewBag.TypePropertyId = this.DbContextContainer.TypePropertyData.GetAllTypePropertySelect();
            this.ViewBag.OwnerId = this.DbContextContainer.ApplicationUserData.GetAllUsersSelect();

            return this.View();
        }

        /// POST: Properties/Create
        /// <summary>
        /// The create.
        /// </summary>
        /// <param name="vm">
        /// The vm.
        /// </param>
        /// <param name="returnUrl">
        /// The return Url.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Create(EditPropertyViewModel vm, string returnUrl)
        {
            this.ViewBag.ReturnUrl = returnUrl;
            
            Comunity propertyComunity = this.DbContextContainer.ComunityData.GetComunity(vm.ComunityId);
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            if (propertyComunity != null)
            {
                var isDirectorsBoardComunity = this.User.IsInRole(RoleNames.RoleDirectorsBorard)
                                               && (this.DbContextContainer.ApplicationUserData
                                                       .GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo
                                                       .ManagedComunities.Contains(propertyComunity) || this
                                                       .DbContextContainer.ApplicationUserData
                                                       .GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo
                                                       .PresidedComunities.Contains(propertyComunity));

                if (isAdmin || isDirectorsBoardComunity)
                {
                    if (this.ModelState.IsValid)
                    {
                        try
                        {
                            Property comunity = this.PropertyVmToNewProperty(vm);
                            this.DbContextContainer.DbContext.Properties.Add(comunity);
                            this.DbContextContainer.DbContext.SaveChanges();

                            return this.RedirectToIndex(returnUrl);
                        }
                        catch (Exception e)
                        {
                            this.ViewBag.ComunityId = this.DbContextContainer.ComunityData.GetAllManagedComunitiesSelect(this.User.Identity.GetUserId());
                            this.ViewBag.TypePropertyId = this.DbContextContainer.TypePropertyData.GetAllTypePropertySelect();
                            this.ViewBag.OwnerId = this.DbContextContainer.ApplicationUserData.GetAllUsersSelect();
                            return this.View(vm);
                        }
                    }
                }
            }
            else
            {
                this.ModelState.AddModelError("TypePropertyId", Strings.RequiredField);
                this.ModelState.AddModelError("ComunityId", Strings.RequiredField);
            }

            this.ViewBag.ComunityId = this.DbContextContainer.ComunityData.GetAllManagedComunitiesSelect(!isAdmin ? this.User.Identity.GetUserId() : null);
            this.ViewBag.TypePropertyId = this.DbContextContainer.TypePropertyData.GetAllTypePropertySelect();
            this.ViewBag.OwnerId = this.DbContextContainer.ApplicationUserData.GetAllUsersSelect();
            return this.View(vm);
        }

        /// GET: Properties/Edit/5
        /// <summary>
        /// The edit.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <param name="returnUrl">
        /// The return Url.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Edit(Guid? id, string returnUrl)
        {
            this.ViewBag.ReturnUrl = returnUrl;

            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            if (id == null || id == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Property property = this.DbContextContainer.PropertyData.GetPropertyById(id);

            if (property == null)
            {
                return this.HttpNotFound();
            }

            var isDirectorsBoardComunity = this.User.IsInRole(RoleNames.RoleDirectorsBorard)
                                           && (this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.ManagedComunities.Contains(property.Comunity)
                                               || this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.PresidedComunities.Contains(property.Comunity));

            if (!isAdmin && !isDirectorsBoardComunity)
            {
                return this.HttpNotFound();
            }

            EditPropertyViewModel vm = this.PropertyModelToVm(property);

            this.ViewBag.ComunityId = this.DbContextContainer.ComunityData.GetAllManagedComunitiesSelect(!isAdmin ? this.User.Identity.GetUserId() : null);

MyNeighborhood/MyNeighborhood/Views/Property/Create.cshtml
@using MyNeighborhood.App_GlobalResources
@model MyNeighborhood.Models.EditPropertyViewModel

@{
    ViewBag.Title = Strings.CretePropertiesTitle;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Property", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.Partial("EditPropertyInfo")
}

@if (ViewBag.ReturnUrl != null)
{
    <div>
        <button type="button" class="btn btn-default"
                onclick="window.location.href = '@ViewBag.ReturnUrl'">
            @Strings.BackToEditComunity
        </button>
    </div>
}
else
{
    <div>
        <button type="button" class="btn btn-default"
                onclick="window.location.href = '@Url.Action("Index", "Property")'">
            @Strings.BackToList
        </button>
    </div>
}

MyNeighborhood/MyNeighborhood/Views/Property/Edit.cshtml
@using MyNeighborhood.App_GlobalResources
@model MyNeighborhood.Models.EditPropertyViewModel

@{
    ViewBag.Title = Strings.EditPropertiesTitle;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Property", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.Partial("EditPropertyInfo")
}

@if (ViewBag.ReturnUrl != null)
{
    <div>
        <button type="button" class="btn btn-default"
                onclick="window.location.href = '@ViewBag.ReturnUrl'">
            @Strings.BackToEditComunity
        </button>
    </div>
}
else
{
    <div>
        <button type="button" class="btn btn-default"
                onclick="window.location.href = '@Url.Action("Index", "Property")'">
            @Strings.BackToList
        </button>
    </div>
}



<script>
    $(document).ready(function() {
        $("#OwnerId").val('@(Model?.OwnerId ?? 0)');
        $("#ComunityId").val('@(Model?.ComunityId)');
        $("#TypePropertyId").val('@(Model?.TypePropertyId)');
    });
</script>

MyNeighborhood/MyNeighborhood/Views/Property/EditPropertyInfo.cshtml
@using MyNeighborhood.App_GlobalResources
@model MyNeighborhood.Models.EditPropertyViewModel

<div class="form-horizontal">
    <h4>Property</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyNumber</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Num, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Num, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyFloor</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Floor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Floor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyDoor</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Door, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Door, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyOwner</label>
        <div class="col-md-10">
            @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyComunity</label>
        <div class="col-md-10">
            @Html.DropDownList("ComunityId", null, htmlAttributes: new { @class = "form-control", required = "true" })
            @Html.ValidationMessageFor(model => model.ComunityId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.PropertyType</label>
        <div class="col-md-10">
            @Html.DropDownList("TypePropertyId", null, htmlAttributes: new { @class = "form-control", required = "true" })
            @Html.ValidationMessageFor(model => model.TypePropertyId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 col-xs-12">
            <button type="submit" class="btn btn-primary">@Strings.ConfirmButton</button>
        </div>
    </div>
</div>

MyNeighborhood/MyNeighborhood/Views/Property/Index.cshtml
@using MyNeighborhood.App_GlobalResources
@using MyNeighborhood.Models
@model IEnumerable<MyNeighborhood.Models.Property>

@{
    var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);
    var isNeighbor = this.User.IsInRole(RoleNames.RoleNeighbor);
}

<section>
    <div class="container">
        @if (!isNeighbor)
        {
            <div class="padding-bottom10">
                <button type="button" class="btn btn-primary" onclick="window.location.href = '@Url.Action("Create", "Property", new { returnUrl = ViewBag.ReturnUrl })'">@Strings.CreateProperty</button>
            </div>
        }
        <table class="dataTable stripe row-border hover collapsed table-responsive" data-responsive='{"details":{"type":"column", "target":3}}'>
            <thead>
                <tr>
                    <th>@Strings.PropertyNumber</th>
                    <th>@Strings.PropertyFloor</th>
                    <th>@Strings.PropertyDoor</th>
                    <th>@Strings.PropertyOwner</th>
                    <th>@Strings.PropertyComunity</th>
                    <th>@Strings.PropertyType</th>
                    <th data-priority="1">&nbsp;</th>
                    <th data-priority="2">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Number)</td>
                        <td>@Html.DisplayFor(m => item.Floor)</td>
                        <td>@Html.DisplayFor(m => item.Door)</td>
                        <td>@Html.DisplayFor(m => item.UserInfo.Name)</td>
                        <td>@Html.DisplayFor(m => item.Comunity.Name)</td>
                        <td title="@item.Type.Description">@Html.DisplayFor(m => item.Type.Name)</td>
                        <td>
                            @if (!isNeighbor)
                            {
                                <button type="button" class="btn btn-primary"
                                        onclick="window.location.href = '@Url.Action("Edit", "Property", new { id = item.Id, returnUrl = ViewBag.ReturnUrl })'">
                                    @Strings.Edit
                                </button>
                            }
                            @if (isAdmin)
                            {
                                <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("Delete", "Property", new { id = item.Id, returnUrl = ViewBag.ReturnUrl })'">@Strings.Delete</button>
                            }
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>