MyNeighborhood/MyNeighborhood/Models/Comunity.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Comunity.cs" company="MyNeigborhood">
//   Pascual Maestre. MyNeighborhood.
// </copyright>
// <summary>
//   Defines the Comunity type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace MyNeighborhood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// The comunity.
    /// </summary>
    public class Comunity
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the street adress.
        /// </summary>
        [Required]
        public string StreetAdress { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [Required]
        public Status Status { get; set; }

        #region Relationship

        /// <summary>
        /// Gets or sets the properties of the user (houses, parking garages, ...)
        /// </summary>
        public ICollection<Property> Properties { get; set; }

        /// <summary>
        /// Gets or sets the director boards members.
        /// </summary>
        [InverseProperty("ManagedComunities")]
        public ICollection<UserInfo> DirectorBoardMembers { get; set; }

        /// <summary>
        /// Gets or sets the president id.
        /// </summary>
        [ForeignKey("President")]
        public int? PresidentId { get; set; }

        /// <summary>
        /// Gets or sets the president.
        /// </summary>
        public UserInfo President { get; set; }

        #endregion
    }
}

MyNeighborhood/MyNeighborhood/Controllers/ComunitiesController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ComunitiesController.cs" company="MyNeighborhood">
//   Pascual Maestre. MyNeighborhood.
// </copyright>
// <summary>
//   Defines the ComunitiesController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace MyNeighborhood.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Net;
    using System.Web.Mvc;

    using global::MyNeighborhood.Models;

    using Microsoft.AspNet.Identity;

    /// <summary>
    /// The comunities controller.
    /// </summary>
    [Authorize]
    public class ComunitiesController : MyNeighborhood
    {
        /// GET: Comunities
        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Index()
        {
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            var comunities = this.DbContextContainer.ComunityData.GetAllManagedComunities(isAdmin ? null : this.User.Identity.GetUserId());

            return this.View(comunities);
        }

        /// GET: Comunities/Create
        /// <summary>
        /// The create.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator)]
        public ActionResult Create()
        {
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            if (!isAdmin)
            {
                return this.HttpNotFound();
            }

            this.ViewBag.PresidentId = this.DbContextContainer.ApplicationUserData.GetPresidentableUsers();

            return this.View();
        }

        /// POST: Comunities/Create
        /// <summary>
        /// The create.
        /// </summary>
        /// <param name="vm">
        /// The vm.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.RoleAdministrator)]
        public ActionResult Create(EditComunityViewModel vm)
        {
            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

            if (this.ModelState.IsValid && isAdmin)
            {
                Comunity comunity = this.ComunityVmToNewComunity(vm);
                this.DbContextContainer.DbContext.Comunities.Add(comunity);
                this.DbContextContainer.DbContext.SaveChanges();

                comunity = this.DbContextContainer.ComunityData.GetComunity(comunity.Id);

                if (comunity.President != null)
                {
                    this.ChangeUserRole(comunity.President.ApplicationUser, RoleNames.RoleDirectorsBorard);
                    comunity.President.ManagedComunities.Add(comunity);
                    comunity.President.PresidedComunities.Add(comunity);
                }

                this.DbContextContainer.DbContext.SaveChanges();

                return this.RedirectToAction("Index");
            }

            this.ViewBag.PresidentId = this.ViewBag.PresidentId = this.DbContextContainer.ApplicationUserData.GetPresidentableUsers();
            return this.View(vm);
        }

        /// GET: Comunities/Edit/5
        /// <summary>
        /// The edit.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Edit(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Comunity comunity = this.DbContextContainer.ComunityData.GetComunity(id);

            if (comunity == null || comunity.Status == Status.Deactivate)
            {
                return this.HttpNotFound();
            }

            var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);
            var isDirectorsBoardComunity = this.User.IsInRole(RoleNames.RoleDirectorsBorard)
                                   && (this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.ManagedComunities.Contains(comunity)
                                   || this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.PresidedComunities.Contains(comunity));

            if (!isAdmin && !isDirectorsBoardComunity)
            {
                return this.HttpNotFound();
            }

            EditComunityViewModel vm = this.ComunityModelToVm(comunity);

            this.ViewBag.PresidentId = this.DbContextContainer.ApplicationUserData.GetPresidentableUsersByCounity(comunity.Id);
            return this.View(vm);

        }

        /// POST: Comunities/Edit/5
        /// <summary>
        /// The edit.
        /// </summary>
        /// <param name="vm">
        /// The vm.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.RoleAdministrator + ", " + RoleNames.RoleDirectorsBorard)]
        public ActionResult Edit(EditComunityViewModel vm)
        {
            if (this.ModelState.IsValid)
            {
                Comunity comunity = this.ComunityVmToModel(vm);

                var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);
                var isDirectorsBoardComunity = this.User.IsInRole(RoleNames.RoleDirectorsBorard)
                                               && (this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.ManagedComunities.Contains(comunity)
                                                   || this.DbContextContainer.ApplicationUserData.GetApplicationUserById(this.User.Identity.GetUserId()).UserInfo.PresidedComunities.Contains(comunity));

                if ((!isAdmin && !isDirectorsBoardComunity) || comunity.Status == Status.Deactivate)
                {
                    return this.HttpNotFound();
                }

                this.DbContextContainer.ComunityData.Save(comunity);
                return this.RedirectToAction("Index");
            }
            this.ViewBag.PresidentId = this.DbContextContainer.ApplicationUserData.GetPresidentableUsersByCounity(vm.Id);
            return this.View(vm);
        }

        /// <summary>
        /// The change status.
        /// </summary>
        /// <param name="id">
        /// The user id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [Authorize(Roles = RoleNames.RoleAdministrator)]
        public ActionResult ChangeStatus(Guid? id)
        {
            if (id != null && id != Guid.Empty)
            {
                var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);

                var comunity = this.DbContextContainer.ComunityData.GetComunity(id);

                if (comunity != null && isAdmin)
                {
                    this.DbContextContainer.ComunityData.CahngeStatus(comunity);

                    this.DbContextContainer.ComunityData.Save(comunity);
                }
            }

            return this.RedirectToAction("Index");
        }

        /// <summary>
        /// The dispose.
        /// </summary>
        /// <param name="disposing">
        /// The disposing.
        /// </param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.DbContextContainer.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// The comunity vm to model.
        /// </summary>
        /// <param name="vm">
        /// The vm.
        /// </param>
        /// <returns>
        /// The <see cref="Comunity"/>.
        /// </returns>
        private Comunity ComunityVmToModel(EditComunityViewModel vm)
        {
            var comunity = this.DbContextContainer.ComunityData.GetComunity(vm.Id);

            if (comunity != null && comunity.Status == Status.Activate)
            {
                comunity.Name = vm.Name;
                comunity.StreetAdress = vm.StreetAdress;

                if (comunity.President != null)
                {
                    comunity.President.ManagedComunities.Remove(comunity);
                    comunity.President.PresidedComunities.Remove(comunity);
                }

                comunity.PresidentId = vm.PresidentId;
                comunity.President?.ManagedComunities.Add(comunity);
                comunity.President?.PresidedComunities.Add(comunity);

                return comunity;
            }

            return null;
        }

        /// <summary>
        /// The comunity vm to new cmunity.
        /// </summary>
        /// <param name="vm">
        /// The vm.
        /// </param>
        /// <returns>
        /// The <see cref="Comunity"/>.
        /// </returns>
        private Comunity ComunityVmToNewComunity(EditComunityViewModel vm)
        {
            return new Comunity()
            {
                Id = new Guid(),
                Name = vm.Name,
                StreetAdress = vm.StreetAdress,
                President = this.DbContextContainer.UserData.GetUserInfoById(vm.PresidentId),
                Status = Status.Activate,
            };
        }

MyNeighborhood/MyNeighborhood/Views/Comunities/Create.cshtml
@using MyNeighborhood.App_GlobalResources
@model MyNeighborhood.Models.Comunity

@{
    ViewBag.Title = Strings.CreteComunityTitle;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    @Html.Partial("EditInfoComunity")
}

<div>
    <button type="button" class="btn btn-default" 
            onclick="window.location.href = '@Url.Action("Index", "Comunities")'">
        @Strings.BackToList
    </button>
</div>

MyNeighborhood/MyNeighborhood/Views/Comunities/Edit.cshtml
@using MyNeighborhood.App_GlobalResources
@model MyNeighborhood.Models.EditComunityViewModel

@{
    ViewBag.Title = Strings.EditComunityTitle;
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="container linebutton padding-bottom10">
        <div>
            <button type="button" class="btn btn-default"
                    onclick="window.location.href = '@Url.Action("Index", "Comunities")'">
                @Strings.BackToList
            </button>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.Partial("EditInfoComunity")
        }
    </div>
    <div class="linebutton padding-bottom10 padding-top10">
        <h4>@Strings.UsersTitle</h4>
        @Html.Action("IndexComunity", "Account", new { comunityId = Model.Id })
    </div>
    <div class="padding-bottom10 padding-top10">
        <h4>@Strings.PropertiesTitle</h4>
        @Html.Action("IndexComunity", "Property", new { comunityId = Model.Id })
    </div>
</section>

MyNeighborhood/MyNeighborhood/Views/Comunities/EditInfoComunity.cshtml
@using MyNeighborhood.App_GlobalResources
@using MyNeighborhood.Models
@model MyNeighborhood.Models.EditComunityViewModel

<div class="form-horizontal">
    <h4>Comunity</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">@Strings.ComunityName</label>
        <div class="col-sm-10 col-xs-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@Strings.ComunityAdress</label>
        <div class="col-sm-10 col-xs-12">
            @Html.EditorFor(model => model.StreetAdress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StreetAdress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" >@Strings.ComunityPresident</label>
        <div class="col-sm-10 col-xs-12">
            @Html.DropDownList("PresidentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PresidentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 col-xs-12">
            <button type="submit" class="btn btn-primary">@Strings.ConfirmButton</button>
        </div>
    </div>
</div>

MyNeighborhood/MyNeighborhood/Views/Comunities/Index.cshtml
@using MyNeighborhood.App_GlobalResources
@using MyNeighborhood.Models
@model IEnumerable<MyNeighborhood.Models.Comunity>

@{
    var isAdmin = this.User.IsInRole(RoleNames.RoleAdministrator);
}

<section>
    <div class="container">
        @if (isAdmin)
        {
            <div class="padding-bottom10">
                <button type="button" class="btn btn-primary" onclick="window.location.href = '@Url.Action("Create", "Comunities")'">@Strings.CreateComunity</button>
            </div>
        }
        <table class="dataTable stripe row-border hover collapsed table-responsive" data-responsive='{"details":{"type":"column", "target":3}}'>
            <thead>
                <tr>
                    <th>@Strings.ComunityName</th>
                    <th>@Strings.ComunityAdress</th>
                    <th>@Strings.ComunityPresident</th>
                    <th>@Strings.ComunityNumberDirectorsBoard</th>
                    <th>@Strings.ComunityStatus</th>
                    <th data-priority="1">&nbsp;</th>
                    <th data-priority="2">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Name)</td>
                        <td>@Html.DisplayFor(m => item.StreetAdress)</td>
                        <td>@Html.DisplayFor(m => item.President.Name)</td>
                        <td>@Html.DisplayFor(m => item.DirectorBoardMembers.Count)</td>
                        <td>@(item.Status == Status.Activate ? Strings.Enabled : Strings.Disabed)</td>
                        <td>
                            <button type="button" class="btn btn-primary" @(item.Status == Status.Deactivate ? "disabled" : "")
                                    onclick="window.location.href = '@Url.Action("Edit", "Comunities", new { id = item.Id })'">
                                @Strings.Edit
                            </button>
                            @if (isAdmin)
                            {
                                <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("ChangeStatus", "Comunities", new { id = item.Id })'">@(item.Status == Status.Activate ? Strings.Disable : Strings.Enable)</button>
                            }
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>